### ISSUE TITLE
[Medical History Report] Unassigned issue dates are not sorted. 

### ISSUE THREAD

**Issue by AnalogJ** [fastenhealth/fasten-onprem#101]

**Comment by EasternPA** [comment]
The encounter dates are in no discernible order in the UNASSIGNED category.

![dates unsorted](https://user-images.githubusercontent.com/713544/225750992-85198ea6-5858-41fa-9e90-a6da5942c286.png)

**Comment by AnalogJ** [comment]
This should be fixed with the latest `sortDate` fixes.
