### ISSUE TITLE
[Dashboard] Patient age on linked provider detail page

### ISSUE THREAD

**Issue by EasternPA** [fastenhealth/fasten-onprem#104]
Click on Dashboard. At the bottom, locate your provider. Click the '>' at the far right end of the provider entry. Review your patient data at the top of the next screen.

The birthday shown for me is correct, but the age is off by several years (also, the unit shown is "year," not "years"). I checked the JSON for the patient details and didn't see my age hardcoded in the JSON.

**Comment by Serinus1** [comment]
https://github.com/fastenhealth/fasten-onprem/pull/138
