### ISSUE TITLE
[Sources] Extra or different source shown.

### ISSUE THREAD

**Issue by EasternPA** [fastenhealth/fasten-onprem#106]
When I add a source, a completely unrelated source is shown after the add operation successfully completes. No idea why this one was shown.

![extra sources](https://user-images.githubusercontent.com/713544/225733791-1c5903e3-6f8b-4de3-9059-0f49cbf4e1a4.png)

**Comment by AnalogJ** [comment]
Hey @EasternPA 
Thanks for pointing this out, it was a bug that was caused by the recent introduction of pagination. It's fixed now.
