### ISSUE TITLE
[Sources] Provider Platform should be visible as a tag in the Connect Source popup

### ISSUE THREAD

**Issue by EasternPA** [fastenhealth/fasten-onprem#110]
I'm trying to add Trinity, and I am still determining which one of the identical ones is mine. Can we get a hover hint or hover alt text?

![trinity](https://user-images.githubusercontent.com/713544/225922686-9f289a64-815f-4365-9a74-2e927afe9f50.png)

**Comment by AnalogJ** [comment]
There's now a popup when users attempt to connect their healthcare provider. This popup gives some additional context, including a link to the provider's homepage.

It is missing the Provider type (which shoudl be available as a tag), which may be useful for institutions that have multiple patient portals. I'll update the title for this issue.

**Comment by AnalogJ** [comment]
this information is now present in the `main` branch -- closing :)
