### ISSUE TITLE
UofL health also uses Epic (MyChart)

### ISSUE THREAD

**Issue by ericlathrop** [fastenhealth/fasten-onprem#133]
UofL Health is already supported via one integration, but different parts of the hospital use MyChart, which can be found at https://mychart.uoflhealth.org

**Comment by second2falcon** [comment]
> Hey,
> 
> Thanks for opening the issue. Do you see UofL Health listed in this document - https://open.epic.com/MyApps/Endpoints ?
> 
> These are the only officially supported healthcare institutions that use Epic.

Spaarne Gasthuis (a Dutch hospital chain/group) uses MyChart, but is not found in the API endpoints. I expect that at least hospitals outside of the US are not on that list.

**Comment by AnalogJ** [comment]
@second2falcon Yeah, I think the published epic endpoints list is US-centric. If you're aware of FHIR endpoints/documentation for Dutch institutions, can you comment on this issue: https://github.com/fastenhealth/fasten-onprem/issues/42 ? 

I'd like to have an international FHIR endpoint to test with, but none of the countries/networks in that issue seem to be good candidates (so far).

**Comment by second2falcon** [comment]
> @second2falcon Yeah, I think the published epic endpoints list is US-centric. If you're aware of patient-accessible FHIR endpoints/documentation for Dutch institutions, can you comment on this issue: #42 ?
> 
> I'd like to have an international FHIR endpoint to test with, but none of the countries/networks in that issue seem to be good candidates (so far).

I will look if I can find anything.
