### ISSUE TITLE
[Feature Request] Support for entering lab results manually

### ISSUE THREAD

**Issue by clearscreen** [fastenhealth/fasten-onprem#137]
I have received two lab reports (both blood and urine) from a third party provider in the form of a PDF.

If there were a form to input these lab results manually it would be very useful.

Just in case it helps, here are the types of data I am looking to input manually

```
Cholesterol
HDL
LDL
Cholesterol/HDL Ratio
LDL/HDL Ratio
Triglycerides

Glucose
Alkaline Phosphatase
Total Bilirubin
SGOT (AST)
SGPT (ALT)
Fructosamine
Blood Urea Nitrogen (BUN)
Creatinine
Gamma-Glutamyl Transferase
Total Protein
Albumin
Globulin

Leukocyte Esterase
Urine Temperature
URN PH
URN Specific Gravity
URN Creatinine
URN Glucose
URN Total Protein
URN Protein/Creatinine
URN Red Blood Count
URN White Blood Count
URN Hyaline Casts
URN Granular Casts
Nicotine Metabolites, URN
URN Blood

Anti-HCV (Hepatitis C)
HBS-AG (Hepatitis B)
HIV
```

Thank you!

**Comment by flintstones-fred** [comment]
> Hey @clearscreen thanks for opening this issue and supporting the project!
> 
> I'm currently focused on the [widget-based dashboard](https://github.com/fastenhealth/fasten-onprem/issues/21) and adding support for [Kaiser Permanente](https://github.com/fastenhealth/fasten-onprem/issues/19), but this is definitely on my to-do list.
> 
> Thanks again!

Actually, a couple of simple things that I would like to add to the list above instead of creating a new issue - 

Weight
Blood Pressure

**Comment by AnalogJ** [comment]
https://lhcformbuilder.nlm.nih.gov/

**Comment by AnalogJ** [comment]
closing as completed in v1!
