### ISSUE TITLE
Docker images should be tagged with release version

### ISSUE THREAD

**Issue by ericlathrop** [fastenhealth/fasten-onprem#147]
The last tagged version is v0.0.8. Maybe a GitHub action could be setup to automatically tag the images as releases are made?

**Comment by AnalogJ** [comment]
You're right, that's weird. Let me see if I can figure out why the tagging isn't working.

**Comment by AnalogJ** [comment]
Looks like this is related to https://github.com/orgs/community/discussions/16244

I though my fixes in 0.1.0 would fix it, but unfortunately they didn't

**Comment by AnalogJ** [comment]
finally fixed with v0.1.3 release. Using https://github.com/marketplace/actions/github-app-token to generate token, which triggers Docker image build when a new release is created. 

Thanks for opening this issue @ericlathrop, sorry it's taken so long to fix :/
