### ISSUE TITLE
Unstick the footer, put at the bottom of the page

### ISSUE THREAD

**Issue by AnalogJ** [fastenhealth/fasten-onprem#160]
> Please unstick the footer (copyright notice). I don't need it taking up expensive screen space at the bottom of the browser. Keep it at the bottom of the page, not the window. It's prevents you from seeing the last line of content.
> https://old.reddit.com/r/DataHoarder/comments/12pg3bu/fasten_health_open_source_selfhosted_personal/jl0m2il/

**Comment by GauravMakhijani** [comment]
I have successfully resolved the footer placement issue on website by removing the class "fixed-bottom" . The footer now at the bottom of the page consistently. I have submitted a pull request for review. Your feedback is greatly appreciated.
