### ISSUE TITLE
change all routerLinks to be ctrl-clickable (open in new tab)

### ISSUE THREAD

**Issue by AnalogJ** [fastenhealth/fasten-onprem#161]
If you click on any link in Fasten, it will route you to the new page, you cannot right click and open on in new window.

> I'd be nice if clickable entries were actually links you could open in new tabs. If I want to compare some reports, I'd to be able to open them in multiple tabs. 
> https://old.reddit.com/r/DataHoarder/comments/12pg3bu/fasten_health_open_source_selfhosted_personal/jl0m2il/

**Comment by tarunsamanta2k20** [comment]
In which file those links are present?

**Comment by AnalogJ** [comment]
this should be complete now.
