### ISSUE TITLE
Access Token timeout during sync

### ISSUE THREAD

**Issue by AnalogJ** [fastenhealth/fasten-onprem#175]
Some providers have access tokens that expire fairly quickly (10m for Cerner). This can cause issues for users attempting to sync large patient histories as these tokens may expire before the sync completes. 

Fasten attempts to add the `offline` scope where possible, but some providers do not support `offline` scope with public clients. 

Investigate potential solutions for this:

- [ ] heavily parallelize requests (already partially done)
- [ ] refresh the access token?
- [ ] allow users to continue where they left off?

**Comment by OhHeyAlan** [comment]
I found that I can get a little more data if I click sync. Nothing significant though.
