### ISSUE TITLE
SQL Logic error upgrading 0.0.12 -> 0.1

### ISSUE THREAD

**Issue by philipcristiano** [fastenhealth/fasten-onprem#187]
When upgrading from 0.0.12 to 0.1.2 (`main`tagged package with `sha256:5f92476e7001ab91ab37a8d9f4c778ae135f03cc43b97254af39079da0f779df` ) a SQL error occurs

```
/go/src/github.com/fastenhealth/fastenhealth-onprem/backend/pkg/models/database/utils.go:14 SQL logic error: Cannot add a NOT NULL column with default value NULL (1)
[2.048ms] [rows:0] ALTER TABLE `related_resources` ADD `resource_base_source_id` text NOT NULL
```

**Comment by AnalogJ** [comment]
ah, this is probably related to the fact that the DB schema has changed significantly between fasten v0.0.x and v.0.1.x
The changes are not backwards compatible. 
You'll need to delete your database file and restart the container

**Comment by philipcristiano** [comment]
Is there anyway to migrate the data? I'd rather not lose the data I've entered. The release notes for 0.1 don't mention recreating the database or migrating things over.

**Comment by AnalogJ** [comment]
Apologies @philipcristiano  but unfortunately its not possible to migrate from the old DB schema to the new one -- Fasten is under heavy development and I expect there to be multiple breaking changes before our stable 1.x release. 

I did add a note about this in our [release notes](https://github.com/fastenhealth/fasten-onprem/releases/tag/v0.1.0) however, I may need to make it more visible. 

- every FHIR resource type is now stored in its own table. This allows us to create additional columns for resource specific search parameter values.
**the new DB schema is incompatible with the old one, so you will need to delete your old .db file if you've persisted it outside of the container**

**Comment by philipcristiano** [comment]
Ah sorry! Guess I was reading too quickly and found query language changes to be less important in my use case than deleting data and didn't pay enough attention to the rest. 

I guess I'll keep an eye out for 1.x!
