### ISSUE TITLE
"An error occurred when accessing healthy-blue-la: '{}'"

### ISSUE THREAD

**Issue by bradydjohnson** [fastenhealth/fasten-onprem#196]
I got this error when trying to add Healthy Blue LA as a source.
<img width="186" alt="fastenhealth 2023-07-25 14-11-25" src="https://github.com/fastenhealth/fasten-onprem/assets/6741590/8a2a35db-fa56-48b1-a561-85ba70a36e8c">

**Comment by AnalogJ** [comment]
Confirmed :grimacing: I was able to replicate this issue locally with the Anthem data source (which also uses CareEvolution EHR under the hood). 

I'll take a look at this issue and get back to you.

**Comment by AnalogJ** [comment]
Hey @bradydjohnson Can you check if the latest `main` (or `sandbox`) docker image fixes the healthy-blue-la issue for you?

**Comment by AnalogJ** [comment]
closing, this should be fixed now.
