### ISSUE TITLE
[Dashboard] Tasks

### ISSUE THREAD

**Issue by AnalogJ** [fastenhealth/fasten-onprem#21]
Development ongoing in https://github.com/fastenhealth/fasten-onprem/tree/grid-development branch. 

![Screenshot 2023-04-26 at 18-25-16 fastenhealth](https://user-images.githubusercontent.com/891875/234768790-e9328970-7392-49ca-839f-4567d4746a0e.png)
![Screenshot 2023-04-26 at 18-24-57 fastenhealth](https://user-images.githubusercontent.com/891875/234768798-32b0da85-67eb-4a29-8710-a1ff2246a960.png)

---

- Replace dashboard with a draggable Widget based UI. 
- See https://github.com/fastenhealth/docs/blob/main/technical/design/UI%20Widgets.md
![builder 8c805691fbce96e66713](https://user-images.githubusercontent.com/891875/211934536-e2433199-9166-4976-a7b3-ed5edd681f82.jpg)

**Comment by AnalogJ** [comment]
https://github.com/gridstack/gridstack.js

**Comment by AnalogJ** [comment]
Stages:
- create DashboardWidgetComponent for various types of charts [(from ChartJS)](https://www.chartjs.org/docs/latest/)
	-

**Comment by AnalogJ** [comment]
similar to 
- https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard_json
- https://github.com/DataDog/metrics-datadog-dashboard/blob/master/dashboards/redis.json

**Comment by AnalogJ** [comment]
- https://stackblitz.com/edit/angular-gridstack-make-widget-example?file=src%2Fapp%2Fapp.component.ts
-

**Comment by AnalogJ** [comment]
# Dashboards/Widget Ideas

- https://www.uplabs.com/posts/doctor-dashboard-for-diabetes-patient
- https://preview.themeforest.net/item/medux-medical-react-dashboard/full_screen_preview/41061766
- https://bootstrapdash.com/demo/azia/v1.0.0/template/dashboard-ten.html

**Comment by AnalogJ** [comment]
FQL - Fasten/Fhir Query Language

- https://simplifier.net/docs/FQL/Home/Syntax/Filtering/Select.guide.md

**Comment by AnalogJ** [comment]
Additional Widgets designed by Discord Practitoners - https://lucid.app/lucidchart/9d115033-b16f-4346-85e2-bde6231d234f/edit?invitationId=inv_8b8d319d-251b-484c-98e7-343622c1bece

**Comment by carlseverson** [comment]
I would have a look at: http://inspiredehrs.org/ and their examples for inspiration and some science behind data visualization in healthcare... although this ebook is specifically geared towards EHRs, there is some applicable information

**Comment by carlseverson** [comment]
d3.js may by extremely helpful here. It is a beautiful library built specifically for data visualization. I don't know how well it plays with angular though.
