### ISSUE TITLE
AthenaHealth Disappeared?

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [fastenhealth/fasten-onprem#238]
I see it on the screenshot on the github but when searching for it in the sources section I can't seem to find it.

**Comment by AnalogJ** [comment]
Hey @Cookie-Monster-Coder 
AthenaHealth is supported, however only in sandbox mode. You can test it out by using the `sandbox` tagged Docker image:

`docker pull ghcr.io/fastenhealth/fasten-onprem:sandbox`

Once you run the container and create an account, you can login to the AthenaHealth test account with the following credentials



Provider | Credentials | Notes
-- | -- | --
AthenaHealth | Username: `phrtest_preview@mailinator.com` Password: `Password1` | [test accounts](https://docs.athenahealth.com/api/guides/onboarding-overview)

We're still testing our production implementation, and I don't yet have a concrete timeline for when AthenaHealth institutions will be available in production, but my hope is within the next 2 weeks or so.

**Comment by AnalogJ** [comment]
closing this, Athena Health endpoints are available as of v0.1.5
