### ISSUE TITLE
Athena Health [bhs-physicians-network] An error occurred while accessing bhs-physicians-network: '{}'

### ISSUE THREAD

**Issue by cardozaj** [fastenhealth/fasten-onprem#249]
Trying to add BHS Physicians Network (Athena Health) and get this error:
`An error occurred while accessing bhs-physicians-network: '{}' `

Console shows this error:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.platform.athenahealth.com/oauth2/v1/token. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.`

**Comment by AnalogJ** [comment]
Hey @cardozaj @Ruthalas @Cronocide 

Can you pull the latest docker image and verify that the Athena providers you were trying to connect are now working? I was able to replicate this issue locally and I've since made a fix

**Comment by Cronocide** [comment]
The providers search has only shown blank tiles for me for the last several releases, so I'm unable to verify right now.

**Comment by AnalogJ** [comment]
Hey @Cronocide I made a number of changes to the provider search engine, which may be why you're running into issues.

What version of Fasten are you on? The version info will be listed in the footer 
Are you using the Docker image or a Desktop app?

**Comment by Cronocide** [comment]
Oops, looks like my container hadn't updated in several weeks (I was still on `f1c120c`!)
I got the container updated and was able to search providers again. I was able to add my provider with Athena Complete Care and it looks like the data import is successful! It's now displaying health data throughout the app. Thank you for the CORS proxy and the followup!

**Comment by AnalogJ** [comment]
Fantastic! Closing this issue :)
