### ISSUE TITLE
Sutter Health source failing

### ISSUE THREAD

**Issue by dqhoang** [fastenhealth/fasten-onprem#290]
Using v0.1.8 Docker on-prem
![image](https://github.com/fastenhealth/fasten-onprem/assets/9045091/e8b469d0-f78b-423f-8a42-834cef0d89c4)

POST to `https://{hostname}/api/secure/source` Failed
Request:
`{
    "source_type": "sutter-health",
    "authorization_endpoint": "https://apiservices.sutterhealth.org/ifs/oauth2/authorize",
    "token_endpoint": "https://apiservices.sutterhealth.org/ifs/oauth2/token",
    "introspection_endpoint": "https://fhir.epic.com/interconnect-fhir-oauth/oauth2/introspect",
    "userinfo_endpoint": "",
    "registration_endpoint": "https://apiservices.sutterhealth.org/ifs/oauth2/register",
    "api_endpoint_base_url": "https://apiservices.sutterhealth.org/ifs/api/FHIR/R4",
    "client_id": "REDACTED",
    "redirect_uri": "https://lighthouse.fastenhealth.com/v1/callback/epic",
    "scopes_supported": [
        "fhirUser",
        "openid",
        "profile"
    ],
    "issuer": "https://fhir.epic.com",
    "grant_types_supported": [
        "authorization_code"
    ],
    "response_types_supported": [
        "code"
    ],
    "aud": "https://apiservices.sutterhealth.org/ifs/api/FHIR/R4",
    "code_challenge_methods_supported": [
        "S256"
    ],
    "confidential": false,
    "cors_relay_required": false,
    "patient": "REDACTED",
    "access_token": "REDACTED",
    "id_token": "REDACTED",
    "dynamic_client_registration_mode": "user-authenticated",
    "expires_at": 1698344289
}`

Response:
`{"success":false}`

Docker logs:
`2023/10/26 17:18:09 Error Response body: {
time="2023-10-26T17:18:08Z" level=warning msg="This client requires a dynamice client registration, starting registration process" type=web
  "error": "invalid_request",
  "error_description": null
}
time="2023-10-26T17:18:09Z" level=error msg="An error occurred while retrieving access token for dynamic client an error occurred while reading dynamic client token response, status code was not 200: 400" type=web`

**Comment by AnalogJ** [comment]
hey @dqhoang I have a couple of questions:

- Did you see this message after successfully authenticating on your patient portal and being redirected back to Fasten?
- are you on Discord? I'd love to do a live-debugging session with you if possible.

**Comment by dqhoang** [comment]
Hi @AnalogJ,

Yes this is after successful authentication with Sutter.

Yes, but i won't be able to jump on my personal machine till this evening (pacific time)

**Comment by AnalogJ** [comment]
Hey @dqhoang apologies I missed this message.
Just ping me on Discord when you have some time, I'll jump and we can figure out whats going on here
