### ISSUE TITLE
CCDA / HLv7 conversion to FHIR R4

### ISSUE THREAD

**Issue by AnalogJ** [fastenhealth/fasten-onprem#291]
- https://github.com/microsoft/FHIR-Converter
- https://ccda.aidbox.app/v2/ccda-fhir
- https://github.com/HL7/C-CDA-Examples/blob/master/Documents/CCD/CCD%202/CCD.xml
- ref #42 
- https://github.com/GoogleCloudPlatform/healthcare-data-harmonization
- https://github.com/HL7/ccda-to-fhir
- https://github.com/hl7/ccda-on-fhir
- https://github.com/LinuxForHealth/hl7v2-fhir-converter

**Comment by hkamran80** [comment]
- https://confluence.hl7.org/display/CGP/C-CDA+to+and+from+US+Core+Mapping
- https://hl7.org/fhir/us/ccda/
- https://www.devdays.com/wp-content/uploads/2020/12/vobgc_201118_OliverEgger_MapCDAtoFHIRandBack.pdf
- https://github.com/hl7ch/cda-fhir-maps/tree/master
- https://github.com/HL7/CDA-core-sd
- https://github.com/Vermonster/fhir-kit-mapping-language
- https://github.com/ahdis/cda-core-2.0/blob/develop/tutorial.md

**Comment by hkamran80** [comment]
Based on this [Open Epic page](https://open.epic.com/CountrySpecific/), most international Epic users use HL7 CDA documents.

**Comment by AnalogJ** [comment]
@hkamran80  good callout, though I'm not sure if it means much if the international health systems don't provide patient access API endpoints. 

---

On a different note, I was playing around with Microsoft's FHIR-Converter project, and was able to get it to build locally, standalone - [fastenhealth/FHIR-Converter](https://github.com/fastenhealth/FHIR-Converter/blob/docker-build/Dockerfile)

However, after testing it out with some CCDA files (thanks @webysther), it seems that the included mapping templates are not very good. They are missing many resources that are generated/converted when using https://ccda.aidbox.app/v2/ccda-fhir

I'm not sure if you're interested in taking this on @hkamran80, but if we could get CCDA & HL7 conversion working, that would be incredible.

**Comment by hkamran80** [comment]
I can take a swing at it.

**Comment by AnalogJ** [comment]
Sweet. One "hacky" but potentially quick solution I was thinking about was just throwing CCDA input and the Aidbox FHIR output at ChatGPT, and seeing if it could generate liquid templates that were better than the existing ones. 

We might need to "train" it on the existing liquid templates though

**Comment by AnalogJ** [comment]
basically: `existing templates` + `CCDA input` = `crappy FHIR output`. 

How can we change the `templates` so that `new templates` + `CCDA input` = `aidbox FHIR output`

**Comment by hkamran80** [comment]
That could work. Do you have some C-CDA test files?

**Comment by AnalogJ** [comment]
https://github.com/HL7/C-CDA-Examples/blob/master/Documents/CCD/CCD%202/CCD.xml and https://github.com/HL7/C-CDA-Examples/blob/master/Documents/CCD/CCD%201/CCD.XML might be a good place to start

**Comment by chaseastewart** [comment]
@AnalogJ I happened to come across this issue. For fun I've been porting FHIR-Converter to [python-fhir-converter](https://github.com/chaseastewart/fhir-converter). I've made a few changes to the templates to make them better. They are certainly not perfect. Feel free to use, provide feedback, contribute or disregard.

**Comment by AnalogJ** [comment]
Hey @chaseastewart 
That looks pretty cool! 
Actually, I should probably close this issue. The AidBox/Health Samurai team has generously donated us a license to their CCDA -> FHIR software, so we're just using that. 

Good luck with [fhir-converter](https://chaseastewart.github.io/fhir-converter/)! I'll keep an eye on it incase we ever need it :)

**Comment by chaseastewart** [comment]
@AnalogJ That cool. I believe the reason for the previous limitation with the templates you previously mentioned what an incorrect assumption in MS's reference templates only looking for the required section template OIDs. Running the templates with this fix generates quite a bit more data than AidBox/Health Samurai.

**Comment by AnalogJ** [comment]
@chaseastewart hm, interesting.
Would you be willing to open a PR against https://github.com/fastenhealth/FHIR-Converter with the change you mentioned so I can try it out?

**Comment by AnalogJ** [comment]
@chaseastewart oh apologies, I might have misunderstood what you were saying. You're repo is a port of microsoft/Fhir-Converter in Python right? Im guessing you're saying the fix is already in your repo?

One of the reasons why I was intrigued by the Microsoft/fhir-converter is that it was written in C# and could be packaged up into a static binary. Fasten is written in Go, and needs to support Docker & Windows/Mac Desktop Apps. Compiled simple binaries are much easier to distribute for us compared to an app that needs a python runtime env. 

any-chance you're willing to port FHIR-Converter to Go? 😆
