### ISSUE TITLE
Broken FAQ link 

### ISSUE THREAD

**Issue by jmandel** [fastenhealth/fasten-onprem#307]
https://docs.fastenhealth.com/ has a "see FAQs"  link that leads to a 404.

>See FAQs for common questions (& answers) regarding Fasten

https://docs.fastenhealth.com/FAQs.md

**Comment by AnalogJ** [comment]
Thanks for pointing that out. I wrote the docs in a markdown editor, and I missed the `.md` extensions when I deployed to Github Pages. 

Here's the correct link:

- [https://docs.fastenhealth.com/faqs.html](https://docs.fastenhealth.com/faqs.html)

I'm deploying a fix now :)

**Comment by AnalogJ** [comment]
fixed in https://github.com/fastenhealth/docs/commit/01a5ce84f8144679e5d1f9803410c2fc9f885460

Thanks for opening this issue @jmandel !
