### ISSUE TITLE
Community Healthcare System uses Epic (MyChart)

### ISSUE THREAD

**Issue by mswolfer** [fastenhealth/fasten-onprem#320]
I couldn't find an option for my provider: https://mychart.comhs.org

It's on the page https://open.epic.com/MyApps/Endpoints:
Community Healthcare System	https://webproxy.comhs.org/FHIR/api/FHIR/DSTU2/

**Comment by AnalogJ** [comment]
Hey @mswolfer 
I was able to find `Community Healthcare System` when using the search:
<img width="928" alt="Screen Shot 2023-11-17 at 2 08 53 PM" src="https://github.com/fastenhealth/fasten-onprem/assets/891875/7aea31a6-253f-4b89-ae4f-ec02d17c777a">

Are you using the `:sandbox` or the `:main` flavor of the docker image?

https://github.com/fastenhealth/fasten-onprem#getting-started

**Comment by mswolfer** [comment]
Oh my gosh. I’m sorry. I don’t know how I missed it, or if I didn’t type out the whole provider name.

I connected it and it’s pulling in records. Thanks for the fantastic work!
