### ISSUE TITLE
[Feature request] Google fit integration?

### ISSUE THREAD

**Issue by ignacio82** [fastenhealth/fasten-onprem#324]
Do you have any plans for creating a Google fit integration? Google fit has a lot of useful data such as weight, sleep, heart rate, etc.

**Comment by AnalogJ** [comment]
yep, see #150 

Feel free to comment there :)

**Comment by AnalogJ** [comment]
closing, but feel free to reopen/comment if there's something missing from #150 that you want to bring my attention to :)
