### ISSUE TITLE
Aetna Source issue

### ISSUE THREAD

**Issue by dunecokc** [fastenhealth/fasten-onprem#33]
Trying to add the Aetna source immediately results in:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<status>
<statusCode>400</statusCode>
<detail>Bad Request</detail>
<severity>E</severity>
<additionalStatus>
<statusCode>400</statusCode>
<serviceName>v1fhirserverauthoauth2authorization</serviceName>
<detail>Missing client_id in Request</detail>
<severity>E</severity>
<loginAttempts>No Login Attempts made</loginAttempts>
</additionalStatus>
</status>
```

Url:
https://vteapif1.aetna.com/fhirdemo/v1/fhirserver_auth/oauth2/authorize?redirect_uri=https%3A%2F%2Flighthouse.fastenhealth.com%2Fv1%2Fcallback%2Faetna&response_type=code&response_mode=fragment&state=3b587e1c-7544-4a35-a8b8-383d8e337b5f&client_id=&scope=fhirUser+launch%2Fpatient+patient%2F*.read+profile&aud=https%3A%2F%2Fvteapif1.aetna.com%2Ffhirdemo%2Fv1%2Fpatientaccess&code_challenge=Tgfyx_93THXCgpdtQwDFAuaD8wdLP3vgmTomPhbO5xk&code_challenge_method=S256

Installed via Docker from today's email.

**Comment by AnalogJ** [comment]
closing. We now have Production access to Aetna. 

However, it seems that Aetna only allows medicare users to access their data via third party apps. :( 👎 

> What members can share health data with third-party apps?
>
> This functionality is currently only available to members of health plans under certain government programs, like Medicare, Medicaid, and Qualified Health Plans on the Federally Facilitated Exchanges. **Aetna’s commercial health plans are not supported**. You may use this platform to share data with third-party apps if you are a member of any of the following plans:
>
> source: https://www.aetnabetterhealth.com/share-health-data-guide.html


If you're an Aetna user and you want to use a third party app to access your data, you may want to file a complaint here: https://www.aetnabetterhealth.com/contact-us.html
