### ISSUE TITLE
Multi-Arch Docker Images

### ISSUE THREAD

**Issue by kaustubh105** [fastenhealth/fasten-onprem#34]
It would be nice to have images for arm64, armv7 etc.

**Comment by AnalogJ** [comment]
https://github.com/AnalogJ/scrutiny/blob/master/.github/workflows/docker-build.yaml

**Comment by AnalogJ** [comment]
As discussed in the Fasten discord, here's the state of Multi-arch builds in Fasten, and a timeline of what's happened:

- when `v0.0.6` was released, we were only building [AMD64 docker images via Github Actions](https://github.com/fastenhealth/fasten-onprem/blob/v0.0.6/.github/workflows/build.yaml)
	- front-end and backend compilation was done separately in a single multi-stage Dockerfile
	- local Docker development and "production" Docker development uses the same Dockerfile

- I attempted to add support for multi-arch builds, by uncommenting the `docker/setup-qemu-action` Github Action step. 
	- this immediately caused build failures related to Yarn timeouts ([`There appears to be trouble with your network connection. Retrying...`](https://github.com/fastenhealth/fasten-onprem/actions/runs/4012466368/jobs/6890932300))
	- I investigated a handful of solutions to this, including `yarn install --network-timeout 100000`, clearing http proxies, changing the registry and clearing the cache -- none of these worked. 
	- I recalled similar issues with [ARM + NPM on QEMU](https://github.com/fastenhealth/fasten-onprem/issues/43) and eventually determined that QEMU + ARM is orders of magnitude slower, and has significant issues when compiling repositories with lots of small files. 
- Eventually I decided to compile the frontend app **outside** of Docker as a separate artifact. 
	- https://github.com/fastenhealth/fasten-onprem/compare/v0.0.6...main
	- This change fixed the "frontend build", however now the backend (Go) build is [failing in a similar way](https://github.com/fastenhealth/fasten-onprem/actions/runs/4016784542/jobs/6900283264) 
	- The assumption is that this is all related to performance issues with [QEMU + ARM](https://github.com/actions/runner-images/issues/2187)


## Possible solutions:

- moving the Go binary build outside of Docker (building multi-arch via GOOS and GOARCH), and then passing the compiled artifacts into the Dockerfile during build. 
	- **NEGATIVES**: local development will be following a non-standard Docker development workflow, instead of running `docker build`, users will be required to run a `make` command to compile outside of docker. Build pipeline becomes more complicated
- move to custom Github Actions runners that support native (non-QEMU emulated) ARM
	- buildjet.com
	- depot.dev
	- Azure Pipeline

**Comment by jacobwgillespie** [comment]
👋 

I've opened PR #54 as an example of the Depot implementation - for some background, Depot is running managed BuildKit builders for both Intel and Arm in AWS, with a persistent 50GB SSD disk, so when build run they are able to instantly reuse the cache, no saving or loading needed. 

For multi-arch builds, Depot launches both an Intel and an Arm VM and uses both, so things stay super fast and skip needing to use QEMU at all.

**Comment by AnalogJ** [comment]
Thanks for all the help @jacobwgillespie @kylegalbraith !
I was able to get everything working, and fix my CI/CD pipeline as well. Depot has been working like a charm, multiarch builds are taking approx 5mins. 

Once again, appreciate all your support, you've been incredibly generous 😃
