### ISSUE TITLE
Allow the ability to disable signup and other user management enhancements

### ISSUE THREAD

**Issue by joestump** [fastenhealth/fasten-onprem#342]
https://github.com/fastenhealth/fasten-onprem/blob/7a77dcdcd679a8441263d9e98166772efa3c5c38/frontend/src/app/pages/auth-signin/auth-signin.component.html#L63C13-L63C13

In addition to disabling signup, allowing OIDC would be nice.

**Comment by hkamran80** [comment]
OIDC/SSO is being tracked in #47
