### ISSUE TITLE
Update sources list with new providers

### ISSUE THREAD

**Issue by xNS5** [fastenhealth/fasten-onprem#354]
Epic updated their list of endpoints at some point recently, and my specific provider is not available through fasten. I'd like to request that the sources list be updated to reflect the new endpoints.

**Comment by AnalogJ** [comment]
Hey @xNS5 is your provider available in the updated list?

https://toolbox.fastenhealth.com

**Comment by xNS5** [comment]
My provider is on the list, however I did get the following error message when adding my provider to Fasten:

An error occurred while initializing external data source connection: '{"fileName":"http://10.0.0.18:32768/web/main.59315f9aa49bb23e.js","lineNumber":1,"columnNumber":2689483,"message":"invalid_grant"}'.

I authorized fasten to maintain access for 1 year. I ran it again and it successfully connected, but this time I only allowed Fasten to maintain access for 1 hour. Not sure whether that played a role in the error message, but I'll do some playing around and submit a ticket if I come up with anything useful.

**Comment by xNS5** [comment]
I attempted to re-create this bug with the 1-year access duration, the error message didn't pop up again. Nothing weird popped up in the network log, so I don't really think there's a need to keep this ticket open.

**Comment by AnalogJ** [comment]
happy to hear it @xNS5!

I made a number of performance tweaks -- I wonder if one of those had some impact on an auth timeout or something similar. 

Either way, if this happens again to you or anybody else, please comment below and I'll reopen this issue
