### ISSUE TITLE
Requesting new Provider: Healow

### ISSUE THREAD

**Issue by phobiac** [fastenhealth/fasten-onprem#358]
https://plus.healow.com/

https://healowhelp.com/2022/03/27/how-do-i-link-an-account-to-my-own/

It appears they have some way to link accounts

**Comment by AnalogJ** [comment]
Hey @phobiac
Healow practices should already be supported. I think they're under the eClinicalWorks platform type

**Comment by phobiac** [comment]
After discussion on the discord it was determined that my specific practice needs to enable API access and that Healow is already supported as noted. Closing this!
