### ISSUE TITLE
Observations with `string`/`boolean` Values display as blank in Charts and fhir-card

### ISSUE THREAD

**Issue by Royal2000H** [fastenhealth/fasten-onprem#360]
Just set up Fasten and playing around with it with real data.

It appears the non-numeric results just show as

"Result: " (just blank)

If I go into the observation and then debug, it does show results such as:
"valueString": "NONREACTIVE" or "valueString": "NEGATIVE" or "valueString": "NOT DETECTED"

**Comment by AnalogJ** [comment]
Ah thanks for calling this out. I had seen it previously but it slipped my mind. 

I had been focused on graphing numerical Observations, but boolean (and string) values require some additional work to display and compare correctly.

**Comment by AnalogJ** [comment]
related #441 
related #440

**Comment by AnalogJ** [comment]
From my discussion with @jean-the-coder  on Discord:

> They're all kind of related to the fact that Fasten only handles numerical values for lab results at the moment, because I display everything on a graph. Anything that's not a number is ignored by chartjs I think. 
>
> A simple workaround for now might just be to display a table of values if any of the lab results is a string.
> 
> https://github.com/fastenhealth/fasten-onprem/blob/main/frontend/src/app/components/report-labs-observation/report-labs-observation.component.html#L56
