### ISSUE TITLE
[Provider Request]: Veradigm / FollowMyHealth

### ISSUE THREAD

**Issue by eliluong** [fastenhealth/fasten-onprem#365]
### Provider/Institution Name

RISSER Orthopaedic Group

### Provider/Institution Website

http://www.risserortho.com/

### Provider EHR Platform

Veradigm

### Anything else we should know?

RISSER Orthopaedic Group provides me with access to FollowMyHealth, which I think is the equivalent of MyChart. I get access to clinical notes, imaging results, etc. It looks like FollowMyHealth is part of Veradigm, which is an EHR (https://veradigm.com/veradigm-ehr/).

**Comment by AnalogJ** [comment]
hey @eliluong 

FollowMyHealth/Veradigm should already be supported. Can you link me to your patient portal login screen? I couldnt find a link on their website.

**Comment by hkamran80** [comment]
I found this page on their site: https://www.risserortho.com/patient-portal/.

**Comment by eliluong** [comment]
Thanks for following up. I got an email to sign up with `https://www.followmyhealth.com/` from them in the past. I can login with that website and will see the documents and data generated by their clinic. I can't seem to find a link to their patient portal on the website. The above link seems to not load the main portal. In any case, their office was recently bought out by Cedars Sinai, so I expect they will transition over to Epic. Therefore, maybe not necessary to waste time figuring this one out.

**Comment by AnalogJ** [comment]
:D ok. I'll close this one out then, but feel free to re-open it if you can't access your records after the transition.
