### ISSUE TITLE
[Bug]: Mercy Health (Arkansas, Louisiana, Mississippi and Texas) sync issue

### ISSUE THREAD

**Issue by madhacker3kxl** [fastenhealth/fasten-onprem#366]
### Contact Details

madhacker3kxl@hotmail.com

### What happened?

I am able to connect to the service just fine. but it has a sync issue.

I get the following attached error message.

### Flavor

Docker

### Version

1.00

### Relevant log output

```shell
{
  "source_id": "**I do not know if this is needed for bug fix**",
  "source_type": "mercy-health-arkansas-louisiana-mississippi-and-texas",
  "error_data": {
    "final": "an error occurred while bulk importing resources from source: An error occurred during request https://epic-fhir.mercy.net/prdfhirstl/api/FHIR/R4/Patient/**redacted patient uuid** - 400 - 400 Bad Request [<html><head><title>Bad Request</title></head><body>400 - The request could not be understood by the server due to malformed syntax. INVALID-MAP-TARGET CID:130</body></html>]"
  }
}
```

**Comment by AnalogJ** [comment]
Hey @madhacker3kxl is this still an issue? We've made a number of changes to the provider logic.

**Comment by madhacker3kxl** [comment]
Sorry about the late reply. I reinstalled fasten-onprem and Mercy Health with Epic does not exist anymore.

**Comment by AnalogJ** [comment]
found the issue, it looks like:

- Tahoe Forest Health System
- CHI St. Vincent
- Riverview Health
- Mercy Health (Arkansas, Louisiana, Mississippi and Texas)

are all part of the same organization, and they got merged together under Riverview Health. 

Let me try to fix that

**Comment by AnalogJ** [comment]
it looks like `Mercy Health - OH, KY` is correctly separated.

**Comment by madhacker3kxl** [comment]
I pulled the latest docker image today. I was able to import my data! I also updated some sources information in the toolbox site.

**Comment by AnalogJ** [comment]
just saw that, thanks @madhacker3kxl 
I merged your provider metadata changes, they'll go out with my next update to the lighthouse

🥳
