### ISSUE TITLE
[Bug]: An error occurred while accessing cabin-creek-health-systems: '{}' 

### ISSUE THREAD

**Issue by iotemylabs** [fastenhealth/fasten-onprem#376]
### Contact Details

brett@iotemylabs.com

### What happened?

When connecting to Cabin Creek Health Systems using Athena Health, and when it tries to download my EMR / EHR, it triggers the error An error occurred while accessing cabin-creek-health-systems: '{}' 

### Flavor

Docker

### Version

main#f1c120c

**Comment by angellk11** [comment]
I'm getting the same error while trying to access a different provider, hosted locally on Docker version main-v1.0.0. The error in the console looks just like the one [posted in Issue #14](https://github.com/fastenhealth/fasten-onprem/issues/14#issuecomment-1364542894).

**Comment by AnalogJ** [comment]
I'm working on some changes to the way source connections work -- including some changes that will make troubleshooting easier. Apologies for the inconvenience -- its pretty difficult to debug issues like this when the errors and bugs are only available on the device/client-side.

**Comment by AnalogJ** [comment]
Hey @angellk11 @iotemylabs 
Can you pull the latest docker image and verify that the Athena providers you were trying to connect are now working? I was able to replicate this issue locally and I've since made a fix

**Comment by angellk11** [comment]
Looks like it's working now, @AnalogJ. Thanks!
