### ISSUE TITLE
Display Medical Imaging files - DICOM

### ISSUE THREAD

**Issue by AnalogJ** [fastenhealth/fasten-onprem#39]
use [ivmartel/dwv](https://github.com/ivmartel/dwv) library for displaying DICOM image

https://ivmartel.github.io/dwv-angular/

**Comment by AnalogJ** [comment]
- Binary resource data model containing data parsed from FHIR resources - https://github.com/fastenhealth/fasten-onprem/blob/main/frontend/src/lib/models/resources/binary-model.ts
- Binary resource display component, used to display various Binary data types (Pdf, Markdown, etc) - https://github.com/fastenhealth/fasten-onprem/blob/main/frontend/src/app/components/fhir/resources/binary/binary.component.html
- Datatype components, contains logic to parse and display specific datatypes (Pdf, Markdown, Html, etc) - https://github.com/fastenhealth/fasten-onprem/tree/main/frontend/src/app/components/fhir/datatypes

**Comment by AnalogJ** [comment]
Looks like theres an `ImagingStudy` resource type that contains the DICOM data. 

# References 
- https://groups.google.com/g/cerner-fhir-developers/c/5E50In55jhI
- http://community.fhir.org/t/how-are-images-like-x-rays-stored-and-retrieved-for-fhir-servers/923/3
- https://terminology.hl7.org/1.0.0/CodeSystem-v2-0291.html
- https://fhir-ru.github.io/codesystem-dicom-dcim.html
- https://github.com/sync-for-science/imaging
- https://confluence.hl7.org/display/HIN/DICOM+and+FHIR+Track

**Comment by trhodeos** [comment]
Looking into this a bit, it seems like DICOM data is actually not included in the FHIR data.. The info in an ImagingStudy is just DICOM metadata. We'd need to import DICOM data from a PACs. I need to confirm w/ some example fhir data, trying to find some now.

Looks like the ImagingStudy has an Endpoint resource on it that contains the DICOM WADO-RS url. https://build.fhir.org/imagingstudy-example-xr.json.html https://build.fhir.org/endpoint-example-wadors.json.html. We'd need to ingest all of the DICOM data from the PACS. Though I'm not sure how auth factors into pulling data from the PACS

## Refs
* https://alvearie.io/blog/imaging-ingestion/
* https://hackmd.io/@victoriatjia/fhir-resources-imagingStudy#How-to-store-DICOM-image-information-in-FHIR-ImagingStudy

**Comment by trhodeos** [comment]
More background:
* https://chat.fhir.org/#narrow/stream/179166-implementers/topic/epic.20dicom
* https://chat.fhir.org/#narrow/stream/179166-implementers/topic/DICOM.20Metadata.20Extension

**Comment by AnalogJ** [comment]
- https://cornerstonejs.github.io/dicomParser/examples/index.html
- http://dcmjs.org/
- https://www.cornerstonejs.org/
- https://ohif.org/get-started

**Comment by AnalogJ** [comment]
updating this thread with my comment from Discord:

---

Now that Fasten supports file uploads, I've started working on DICOM support in PR #116 - https://github.com/fastenhealth/fasten-onprem/pull/116

Basically manually created file attachments are associated with a Condition/Patient in 2 ways:
- DocumentReference (all non-medical imaging attachments) https://www.hl7.org/fhir/R4/documentreference.html 
- DiagnosticReport -> Media (for medical imaging attachments/DICOM files) https://www.hl7.org/fhir/R4/DiagnosticReport.html


ImagingStudy seems to be more focused on a clinical workflows, storing only DICOM metadata, while the actual imaging files are stored on a external server/WADO). Its also **NOT** a USCore resource, which means patients are unlikely to see this resource type returned from the api - https://build.fhir.org/ig/HL7/US-Core/
