### ISSUE TITLE
Attachments not being added to db? [Bug]: 

### ISSUE THREAD

**Issue by BenHolmes** [fastenhealth/fasten-onprem#393]
### Contact Details

github@services.benholmes.net

### What happened?

I create an attachment on an encounter and then it does not appear to be attached and when I return to add an attachment again it looks like I never entered anything.
<img width="111" alt="image7" src="https://github.com/fastenhealth/fasten-onprem/assets/5169182/156be153-531c-44a8-aa16-5d18a6c034cd">
<img width="369" alt="image6" src="https://github.com/fastenhealth/fasten-onprem/assets/5169182/55f26f7f-3e98-4b50-998f-9112024b3b7c">
<img width="643" alt="image5" src="https://github.com/fastenhealth/fasten-onprem/assets/5169182/c7917804-f1f5-406f-b9ec-60f111ed9fbc">
<img width="626" alt="image4" src="https://github.com/fastenhealth/fasten-onprem/assets/5169182/c92ff1c4-ca8d-453b-a4d0-4596b0caf965">
<img width="700" alt="image3" src="https://github.com/fastenhealth/fasten-onprem/assets/5169182/d641607b-603b-472f-be5d-5e4ba2bcd14c">
<img width="874" alt="image2" src="https://github.com/fastenhealth/fasten-onprem/assets/5169182/ff5bf444-74b2-4902-bced-85416238bcc2">
<img width="643" alt="image" src="https://github.com/fastenhealth/fasten-onprem/assets/5169182/0a2166af-1576-48c7-b9fc-9087933b924f">

### Flavor

Docker

### Version

main#1b3e435

**Comment by AnalogJ** [comment]
hey @BenHolmes can you test this PR once the Docker image finishes building?

https://github.com/fastenhealth/fasten-onprem/actions/runs/7703412680

**Comment by BenHolmes** [comment]
> hey @BenHolmes can you test this PR once the Docker image finishes building?
> 
> https://github.com/fastenhealth/fasten-onprem/actions/runs/7703412680

Yeah will do! Thanks😄
