### ISSUE TITLE
[Provider Request]: VA (US Department of Veterans Affairs) [VistA EHR]

### ISSUE THREAD

**Issue by gramaryen** [fastenhealth/fasten-onprem#418]
### Contact Details

green.aarond@gmail.com

### Provider/Institution Name

VA (US Department of Veterans Affairs)

### Provider/Institution Website

https://eauth.va.gov

### Patient Portal Login Website

https://eauth.va.gov/mhv-portal-web/web/myhealthevet/home

### Provider EHR Platform

VistA

### Anything else we should know?

https://www.va.gov/vhie/

"Electronic Record Sharing Options
Beginning April 17, 2020, VA will seamlessly and securely share your electronic health record with community providers who are part of your care team through the [Veterans Health Information Exchange](https://www.va.gov/vhie/) (VHIE)."

**Comment by AnalogJ** [comment]
hey @gramaryen thanks for opening this issue!
We're already working on an integration with the VA. We have support in our sandbox environment already, and we're in the process of getting production approval. Howerver, I expect this to take atleast another couple of weeks. 

Thanks for opening this issue, its a good idea to keep track of the VA status here (instead of just in my email 😄 )

**Comment by AnalogJ** [comment]
Just copy-pasting an update from Discord for everyone following along on Github:

```
I guess it can't always be rainbows and butterflies. I just got some bad news from the VA 😕 
They've decided to deny our self-hosted version access to their production API, stating: VA must consider whether such access advances a shared objective, improves programmatic reputation/visibility, and/or achieves mutual programmatic goals and citing our potential for abuse of their API. 

On the other hand it's not all bad news: they will continue considering production access to their APIs for the desktop version of Fasten.

I've sent them a follow up email asking for more clarifications around the self-hosted denial, asking if there are any legal, procedural or technical changes we can make that would all them to reconsider. I'll continue to keep you all updated.
``

**Comment by AnalogJ** [comment]
VA Health has now been added to Fasten Desktop! closing this issue
