### ISSUE TITLE
[Bug]: Explorer page, binary tab, fails to show images.

### ISSUE THREAD

**Issue by madhacker3kxl** [fastenhealth/fasten-onprem#437]
### What happened?

When viewing the explorer page and in binary tab, click on an image/jpeg shows an error.

![image](https://github.com/fastenhealth/fasten-onprem/assets/1103283/35d42d5d-55df-4f87-86ad-b3acb242bb2e)
![image](https://github.com/fastenhealth/fasten-onprem/assets/1103283/6738fdd4-b68d-416d-b117-b826bb3dcaec)

### Flavor

Docker

### Version

main#e4a73ff

### Relevant log output

```shell
level=error msg="An error occurred while retrieving resource no resource found with source id 6dccfd76-53a1-4ca3-b130-b387f954011e and source resource id aHR0cHM6Ly93d3cubWVyY3kubmV0L3NpdGVzL2RlZmF1bHQvZmlsZXMvZG9jdG9yX2ltYWdlcy9kZXNrdG9wLzE2NTk4ODYwNTktbS5qcGc" type=web
```

**Comment by AnalogJ** [comment]
figured out the issue. We arn't url-encoding the source-resource-id, which is base64 encoded in some cases 

`aHR0cHM6Ly93d3cubWVyY3kubmV0L3NpdGVzL2RlZmF1bHQvZmlsZXMvZG9jdG9yX2ltYWdlcy9kZXNrdG9wLzE2NTk4ODYwNTktbS5qcGc=`

should be:

`aHR0cHM6Ly93d3cubWVyY3kubmV0L3NpdGVzL2RlZmF1bHQvZmlsZXMvZG9jdG9yX2ltYWdlcy9kZXNrdG9wLzE2NTk4ODYwNTktbS5qcGc%3D`

the `=` is a reserved character in URLs.

**Comment by madhacker3kxl** [comment]
Nice catch! Noticed that the log I attached above does not have the "="

**Comment by AnalogJ** [comment]
yep, I'll work on getting that fixed. There's about a dozen different places where we do that, so it might take a bit :(
