### ISSUE TITLE
[Bug]: Blue Cross Blue Shield of Alabama not working

### ISSUE THREAD

**Issue by Alf626** [fastenhealth/fasten-onprem#438]
### What happened?

Can't connect to Blue Cross Blue Shield of Alabama.  Just spins when trying to connect. 

Patient Portal address appears to be missing: https://www.bcbsal.org/mybluecross

### Flavor

Docker

### Version

 main#05a6840

**Comment by AnalogJ** [comment]
Anthem/Blue Cross is known to be broken right now, but we should have a fix shortly. 

Closing this as a dupe of #470
