### ISSUE TITLE
[Provider Request]: Amwell

### ISSUE THREAD

**Issue by Alcatraz077** [fastenhealth/fasten-onprem#443]
### Provider/Institution Name

Amwell

### Provider/Institution Website

https://amwell.com

### Patient Portal Login Website

https://amwell.com/loginConsumer.htm

### Provider EHR Platform

Amwell

### Anything else we should know?

Amwell is a telehealth only provider

**Comment by AnalogJ** [comment]
Registered for a dev account at https://code.amwell.com/
Waiting for my account to be activated

**Comment by AnalogJ** [comment]
Actually, i dont think they are an EHR vendor themselves. They arn't listed in CHPL. 
I think they are just a service provider for healthcare insitutitons.
