### ISSUE TITLE
[Provider Request]: Polyclinic

### ISSUE THREAD

**Issue by phillee** [fastenhealth/fasten-onprem#455]
### Contact Details

i@philip.io

### Provider/Institution Name

Polyclinic / Optum

### Provider/Institution Website

https://www.polyclinic.com/

### Patient Portal Login Website

https://myhealthchart.com/mychart/Authentication/Login?

### Provider EHR Platform

Epic MyChart

### Anything else we should know?

Polyclinic isn't listed as a provider. I believe they were acquired by Optum, but the Optum connections don't seem to work for me, they go to a different portal than the one I use (myhealthchart.com).

**Comment by AnalogJ** [comment]
Hey @phillee Can you search for "The Everett Clinic" and see if you can login there? 

If I'm reading this configuration correctly, they share a Epic EHR (and are both under Optum). Once you confirm I'll create a PolyClinic Brand or alias.

**Comment by AnalogJ** [comment]
This should be fixed. closing :)
