### ISSUE TITLE
[Bug]: Aetna Login Requires PHI Release for

### ISSUE THREAD

**Issue by tetra-archos** [fastenhealth/fasten-onprem#457]
### Contact Details

matt.church.whitlow@gmail.com

### What happened?

Aetna connector doesn't work, when contacting aetna they say I need to fill out a PHI release form, and I don't have the information for Fasten Health to do so.

### Flavor

Docker

### Version

Current

**Comment by AnalogJ** [comment]
Aetna is only supported for govt sponsored plans (not commercial plans) - discussed in #33 
Though the message they sent you is different than what they've shared with me when I last reached out to them. Can you share a link to the PHI form you were given?


> # What members can share health data with third-party apps?
>
 >   This functionality is currently only available to members of health plans under certain government programs, like Medicare, Medicaid, and Qualified Health Plans on the Federally Facilitated Exchanges. Aetna’s commercial health plans are not supported. You may use this platform to share data with third-party apps if you are a member of any of the following plans:
>
>    source: [aetnabetterhealth.com/share-health-data-guide.html](https://www.aetnabetterhealth.com/share-health-data-guide.html)

If you're an Aetna user and you want to use a third party app to access your data, you may want to file a complaint here: [aetnabetterhealth.com/contact-us.html](https://www.aetnabetterhealth.com/contact-us.html)

**Comment by tetra-archos** [comment]
Maybe rename Aetna to Aetana Gov for the time being to delineate, also that Aetnabetterhealth.com link doesn't have my state, for some reason.
