### ISSUE TITLE
[Bug]: syncing health records from Mt Sinai

### ISSUE THREAD

**Issue by zula24** [fastenhealth/fasten-onprem#461]
### What happened?

Added Mt Sinai to Connected Services, logged into Mt Sinai, checked records I wanted FH to access, chose 1 day for length of access, pressed "allow access" and this error popped up:

"An error occurred while finalizing external data
source and starting sync: 'initial record sync failed.
See background jobs page for more details’"

### Flavor

Desktop

### Version

Fasten 2022 | dev

**Comment by AnalogJ** [comment]
Hey @zula24 When you click on the Background jobs page, do you see any additional error data?
