### ISSUE TITLE
[Bug]: Unitedhealthcare Request Fails

### ISSUE THREAD

**Issue by queball1999** [fastenhealth/fasten-onprem#468]
### Contact Details

queproton@duck.com

### What happened?

Hello,

I am trying to add unitedhealthcare as a provider in my locally hosted instance and am greeted by the following:

`An error occurred while initializing external data source connection: '{"stack":"Error: callback error: server_error, description: Cannot invoke \"java.util.List.stream()\" because the return value of \"com.optum.clinicalinterop.authz.eligibility.models.Eligibility.getMemberships()\" is null\n at http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:2705008\n at Generator.next (<anonymous>)\n at De (http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215358)\n at kt (http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215584)\n at http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215659\n at new e (http://192.168.4.5:9090/web/assets/js/lforms/assets/lib/zone.min.js:29:3049)\n at http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215517\n at http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:2706723\n at e.invoke (http://192.168.4.5:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:7205)\n at Object.onInvoke (http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:114508)","message":"callback error: server_error, description: Cannot invoke \"java.util.List.stream()\" because the return value of \"com.optum.clinicalinterop.authz.eligibility.models.Eligibility.getMemberships()\" is null"}'`

Here are the sync logs:
`[SYNC] 2024-05-02 12:08
Status
STATUS_FAILED
Last Updated
2024-05-02 12:08
Completed At
2024-05-02 12:08
{
  "source_id": "00000000-0000-0000-0000-000000000000",
  "brand_id": "5863477c-a178-41fc-b9f4-c881f9e8dbca",
  "checkpoint_data": {
    "brand_id": "5863477c-a178-41fc-b9f4-c881f9e8dbca",
    "code_challenge_method": "S256",
    "endpoint_id": "577a6af3-9fb6-43e2-8bdf-920cf435fe3b",
    "portal_id": "3f7e0791-7bab-46cb-be35-c9729c653eb0",
    "state": "3a644622-fa9d-4aa7-b012-2dd1a579994d"
  },
  "error_data": {
    "error": "{\"stack\":\"Error: callback error: server_error, description: Cannot invoke \\\"java.util.List.stream()\\\" because the return value of \\\"com.optum.clinicalinterop.authz.eligibility.models.Eligibility.getMemberships()\\\" is null\\n    at http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:2705008\\n    at Generator.next (<anonymous>)\\n    at De (http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215358)\\n    at kt (http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215584)\\n    at http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215659\\n    at new e (http://192.168.4.5:9090/web/assets/js/lforms/assets/lib/zone.min.js:29:3049)\\n    at http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215517\\n    at http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:2706723\\n    at e.invoke (http://192.168.4.5:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:7205)\\n    at Object.onInvoke (http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:114508)\",\"message\":\"callback error: server_error, description: Cannot invoke \\\"java.util.List.stream()\\\" because the return value of \\\"com.optum.clinicalinterop.authz.eligibility.models.Eligibility.getMemberships()\\\" is null\"}",
    "stack": "Error: callback error: server_error, description: Cannot invoke \"java.util.List.stream()\" because the return value of \"com.optum.clinicalinterop.authz.eligibility.models.Eligibility.getMemberships()\" is null\n    at http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:2705008\n    at Generator.next (<anonymous>)\n    at De (http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215358)\n    at kt (http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215584)\n    at http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215659\n    at new e (http://192.168.4.5:9090/web/assets/js/lforms/assets/lib/zone.min.js:29:3049)\n    at http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215517\n    at http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:2706723\n    at e.invoke (http://192.168.4.5:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:7205)\n    at Object.onInvoke (http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:114508)",
    "summary": "An error occurred while initializing external data source connection: '{\"stack\":\"Error: callback error: server_error, description: Cannot invoke \\\"java.util.List.stream()\\\" because the return value of \\\"com.optum.clinicalinterop.authz.eligibility.models.Eligibility.getMemberships()\\\" is null\\n    at http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:2705008\\n    at Generator.next (<anonymous>)\\n    at De (http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215358)\\n    at kt (http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215584)\\n    at http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215659\\n    at new e (http://192.168.4.5:9090/web/assets/js/lforms/assets/lib/zone.min.js:29:3049)\\n    at http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215517\\n    at http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:2706723\\n    at e.invoke (http://192.168.4.5:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:7205)\\n    at Object.onInvoke (http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:114508)\",\"message\":\"callback error: server_error, description: Cannot invoke \\\"java.util.List.stream()\\\" because the return value of \\\"com.optum.clinicalinterop.authz.eligibility.models.Eligibility.getMemberships()\\\" is null\"}'"
  }
}`

### Flavor

Docker

### Version

main#3b6d262

### Relevant log output

```shell
{
  "source_id": "00000000-0000-0000-0000-000000000000",
  "brand_id": "5863477c-a178-41fc-b9f4-c881f9e8dbca",
  "checkpoint_data": {
    "brand_id": "5863477c-a178-41fc-b9f4-c881f9e8dbca",
    "code_challenge_method": "S256",
    "endpoint_id": "577a6af3-9fb6-43e2-8bdf-920cf435fe3b",
    "portal_id": "3f7e0791-7bab-46cb-be35-c9729c653eb0",
    "state": "3a644622-fa9d-4aa7-b012-2dd1a579994d"
  },
  "error_data": {
    "error": "{\"stack\":\"Error: callback error: server_error, description: Cannot invoke \\\"java.util.List.stream()\\\" because the return value of \\\"com.optum.clinicalinterop.authz.eligibility.models.Eligibility.getMemberships()\\\" is null\\n    at http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:2705008\\n    at Generator.next (<anonymous>)\\n    at De (http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215358)\\n    at kt (http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215584)\\n    at http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215659\\n    at new e (http://192.168.4.5:9090/web/assets/js/lforms/assets/lib/zone.min.js:29:3049)\\n    at http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215517\\n    at http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:2706723\\n    at e.invoke (http://192.168.4.5:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:7205)\\n    at Object.onInvoke (http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:114508)\",\"message\":\"callback error: server_error, description: Cannot invoke \\\"java.util.List.stream()\\\" because the return value of \\\"com.optum.clinicalinterop.authz.eligibility.models.Eligibility.getMemberships()\\\" is null\"}",
    "stack": "Error: callback error: server_error, description: Cannot invoke \"java.util.List.stream()\" because the return value of \"com.optum.clinicalinterop.authz.eligibility.models.Eligibility.getMemberships()\" is null\n    at http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:2705008\n    at Generator.next (<anonymous>)\n    at De (http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215358)\n    at kt (http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215584)\n    at http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215659\n    at new e (http://192.168.4.5:9090/web/assets/js/lforms/assets/lib/zone.min.js:29:3049)\n    at http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215517\n    at http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:2706723\n    at e.invoke (http://192.168.4.5:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:7205)\n    at Object.onInvoke (http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:114508)",
    "summary": "An error occurred while initializing external data source connection: '{\"stack\":\"Error: callback error: server_error, description: Cannot invoke \\\"java.util.List.stream()\\\" because the return value of \\\"com.optum.clinicalinterop.authz.eligibility.models.Eligibility.getMemberships()\\\" is null\\n    at http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:2705008\\n    at Generator.next (<anonymous>)\\n    at De (http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215358)\\n    at kt (http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215584)\\n    at http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215659\\n    at new e (http://192.168.4.5:9090/web/assets/js/lforms/assets/lib/zone.min.js:29:3049)\\n    at http://192.168.4.5:9090/web/polyfills.5ca82281f9682ff9.js:1:215517\\n    at http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:2706723\\n    at e.invoke (http://192.168.4.5:9090/web/assets/js/lforms/assets/lib/zone.min.js:14:7205)\\n    at Object.onInvoke (http://192.168.4.5:9090/web/main.89a9cc926d70430f.js:1:114508)\",\"message\":\"callback error: server_error, description: Cannot invoke \\\"java.util.List.stream()\\\" because the return value of \\\"com.optum.clinicalinterop.authz.eligibility.models.Eligibility.getMemberships()\\\" is null\"}'"
  }
}
```

**Comment by AnalogJ** [comment]
This looks like a bug on the EHR side `"com.optum.clinicalinterop.authz.eligibility.models.Eligibility.getMemberships()\\\"` -- Fasten isn't written in Java. 

However, if I had to guess, this is related to https://github.com/fastenhealth/fasten-onprem/issues/318

I'm going to close this issue. I'm working on adding some helpful text to warn users that connecting Insurance plans may not work unless they are Medicare/Medicaid/State funded.
