### ISSUE TITLE
Feature Request: Integration of Pet Medical Records in Fasten Health

### ISSUE THREAD

**Issue by queball1999** [fastenhealth/fasten-onprem#469]
I am not sure if anyone else would even be interested in this feature, but now that I have been using Fasten, it would be nice to also store my pet's medical records here as well. Given the integral role pets play in many families, extending Fasten Health’s capabilities to include pet medical records would not only enhance the user experience but also fill a significant need for pet owners. This feature would allow users to consolidate medical information for all family members, pets included, in one central location.

**Comment by AnalogJ** [comment]
To be completely honest, I think this is going to be out of scope for Fasten. 
While I'm sure there's a real need for software that handles medical records for pets, the UI experience (and data structures/sources we integrate with) are designed around human medical records, and probably wouldnt work very well for pets. 

Sorry!
