### ISSUE TITLE
[Provider Request][Epic]: Mercy

### ISSUE THREAD

**Issue by tigew** [fastenhealth/fasten-onprem#483]
### Contact Details

travis@peebles.family

### Provider/Institution Name

Mercy (MO)

### Provider/Institution Website

https://www.mercy.net

### Patient Portal Login Website

https://www.mercy.net/app/login

### Provider EHR Platform

Epic MyChart

**Comment by madhacker3kxl** [comment]
You can get the mercy data using existing "Mercy Health (Arkansas, Louisiana, Mississippi and Texas)"  Even though MO is not listed, it worked for me as I am in OK and the same mercy.net is used.

**Comment by AnalogJ** [comment]
Mercy should already be supported. Closing this issue.
Feel free to reopen if you're still having issues.
