### ISSUE TITLE
[Provider Request]: Memorial Hermann Houston

### ISSUE THREAD

**Issue by cheekoo** [fastenhealth/fasten-onprem#487]
### Provider/Institution Name

Memorial Hermann Houston

### Provider/Institution Website

https://www.memorialhermann.org/services/specialties/mymemorialhermann

### Patient Portal Login Website

https://mychart.memorialhermann.org/MyChart/Authentication/Login?postloginurl=home%3flang%3den

### Provider EHR Platform

My Chart

**Comment by cheekoo** [comment]
https://epicproxy.et1326.epichosted.com/FHIRProxy/api/FHIR/DSTU2/
Above link from - https://open.epic.com/MyApps/Endpoints

Hope this helps.

**Comment by AnalogJ** [comment]
This institution is already supported - "Memorial Hermann"
