### ISSUE TITLE
[Improvement Request] Calendar, upcoming appointments, tasks

### ISSUE THREAD

**Issue by theshabobo** [fastenhealth/fasten-onprem#490]
Would it be possible to add a section to input a calendar of upcoming appointments, tasks, and To-Do's?

Example: I manage my mothers healthcare and she get a lot of Dr. appointments and currently go to google calendar to put her upcoming appointments. I also user google keep for notes, phone numbers, and her account numbers. Also use google tasks to remind myself to setup transportation for her. 

So I am looking to see if it is possible to add these functions to keep all of it in one place. 

Thank you! Love this app!

**Comment by AnalogJ** [comment]
Unfortunately appointment information is categorized as operational data, not clinical data. And as such it is not required to be provided to the patient on request -- atleast not via the patient access apis. 

https://www.healthit.gov/isp/united-states-core-data-interoperability-uscdi#uscdi-v3

Sorry, closing this issue for now as there's not much we can do about it
