### ISSUE TITLE
[Provider Request]: OU Health

### ISSUE THREAD

**Issue by matthmelt** [fastenhealth/fasten-onprem#491]
### Contact Details

mh_soc@redbutterfly.net

### Provider/Institution Name

OU Health

### Provider/Institution Website

https://ouhealth.com

### Patient Portal Login Website

mychart.ouhealth.com

### Provider EHR Platform

Epic MyChart

### Anything else we should know?

This provider is in the list, but when trying to add a source, it hangs indefinitely.

The provider changed to Epic within in the past ~6 months. The MyChart login page is at mychart.ouhealth.com and I'm not sure if perhaps when it was setup the URL was different?

Thank you!

**Comment by matthmelt** [comment]
Please disregard. This link was successful.

**Comment by AnalogJ** [comment]
:D I was just about to respond saying that OU Health is already supported. Thanks for confirming :)
