### ISSUE TITLE
[Bug]: last updated is always wrong

### ISSUE THREAD

**Issue by dwradcliffe** [fastenhealth/fasten-onprem#494]
### What happened?

It seems that the last updated on the dashboard is always `Oct 10, 2018`.

### Flavor

Docker

### Version

main#c5d7717

**Comment by hkamran80** [comment]
It's currently hardcoded in the components.

https://github.com/fastenhealth/fasten-onprem/blob/main/frontend%2Fsrc%2Fapp%2Fpages%2Fdashboard%2Fdashboard.component.html

https://github.com/fastenhealth/fasten-onprem/blob/main/frontend%2Fsrc%2Fapp%2Fcomponents%2Freport-header%2Freport-header.component.html

**Comment by dwradcliffe** [comment]
Duplicate of #22
