### ISSUE TITLE
[Provider Request]: Doctolib

### ISSUE THREAD

**Issue by Froggy232** [fastenhealth/fasten-onprem#520]
### Provider/Institution Name

Doctolib

### Provider/Institution Website

https://www.doctolib.fr

### Patient Portal Login Website

https://www.doctolib.fr/sessions/new/username_sign_in?context=navigation_bar

### Anything else we should know?

Hi,
I don't know if it's possible unfortunally, but this website is literally the official centralized point of all medic professional of France. If it would be possible to integrate to Fasten, french users would no need any other providers to have the integrality of their medical records.
Thanks you a lot!

**Comment by AnalogJ** [comment]
Thanks for the info!

International support is being tracked in #42 so I'm going to close this for now, but thanks for the links and context :)
