### ISSUE TITLE
enhancements to the record editor/creator for manually entering medical history

### ISSUE THREAD

**Issue by AnalogJ** [fastenhealth/fasten-onprem#60]
as discussed in [FHIR Zulip](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Patient-focused.20record.20creator/near/325987483)

We've received constant feedback that users would also like the ability to create records themselves:
- their institution may not be supported by Fasten
- their institution may be international (and not have a patient-accessible portal)
- they have old records that no longer exist
- they have relevant medical data that has never been tracked by an institution
- etc. 

Since our system already uses and understands FHIR documents, we should store patient manually-created documents in the same format, however [FHIR editors](http://docs.smarthealthit.org/fred/) seem complicated, requiring patients to understand the FHIR spec.

---

Some ideas for how medical history can be "manually" ingested by Fasten

- a UI library that generates "simple" forms for each (or multiple) FHIR resource type?
- using the FHIR Questionnaire resource/wizard for prompting users for their medical information?
- an ML based system to parse free-text into records. 
- a simple DSL (similar to FSH) that can generate FHIR records. 
- a question/answer style chatbot for generating records

**Comment by AnalogJ** [comment]
The "Patient Health Record" form in https://lhcforms.nlm.nih.gov/lhcforms is almost exactly what we want. It's a bit dense, but very functional and intuitive.

Autocomplete based on SNOMED/LOINC records would be ideal.

**Comment by AnalogJ** [comment]
> Awesome, would love to see this manual entry be two tiered, with an encounter entry form that allows for selecting previously entered providers / locations / diagnoses / medications while also allowing for the addition of visit type, chief complaint, vitals, progress notes, patient instructions, etc.


https://www.reddit.com/r/selfhosted/comments/12pcna3/fasten_health_open_source_selfhosted_personal/jgol6lm/

**Comment by phobrla** [comment]
> > Awesome, would love to see this manual entry be two tiered, with an encounter entry form that allows for selecting previously entered providers / locations / diagnoses / medications while also allowing for the addition of visit type, chief complaint, vitals, progress notes, patient instructions, etc.
> 
> https://www.reddit.com/r/selfhosted/comments/12pcna3/fasten_health_open_source_selfhosted_personal/jgol6lm/

The [FHIR Form Builder](https://lhcformbuilder.nlm.nih.gov)'s JSON output function may be able to be used with Excel and Regular Expressions to quickly wireframe an encounter addition form.

**Comment by phobrla** [comment]
> Autocomplete based on SNOMED/LOINC records would be ideal.

https://jsfiddle.net/lforms/weaqqbg4/29/ is a demo of this; source is at https://github.com/lhncbc/lforms

**Comment by AnalogJ** [comment]
@phobrla  "Autocomplete based on SNOMED/LOINC records would be ideal." is already in place. Is that feature not working for you?
