### ISSUE TITLE
Linking CVS/MinuteClinic just forwards to provider site

### ISSUE THREAD

**Issue by philipsd6** [fastenhealth/fasten-onprem#65]
When I click on the "CVS Health & Minute Clinic" tile, it launches the https://mychart.minuteclinic.com auth page, but then when I complete authenticating, it just loads the normal MyChart site for CVS/MinuteClinic. Nothing gets added to fasten. 

What am I doing wrong?

**Comment by EasternPA** [comment]
Same.

**Comment by EasternPA** [comment]
Thank you for updating this. If you get this working, I think there would be value in adding CVS' vaccine card and lab test result API as a unique provider in fasten (URL listed in my comment), assuming they host that API separately and haven't just moved everything over there. Not sure if they serve up the QR codes via the API or if fasten would need to generate one from the JSON data returned.

**Comment by AnalogJ** [comment]
Yeah, the Smart Vaccine Cards are a feature that I'd like to support with Fasten as well. Currently immunization & vaccination information is available in the Patient Profile page (not in Smart Vaccine Card format however).
