### ISSUE TITLE
Error when adding Anthem

### ISSUE THREAD

**Issue by kcam01** [fastenhealth/fasten-onprem#99]
I'm getting the following error when trying to add Anthem
An error occurred while accessing anthem: Error: could not find client secret for careevolution.client_secret

**Comment by AnalogJ** [comment]
Hey @kcam01 looks like I broke something with the recent sources update. I'll take a look and get this fixed.

**Comment by AnalogJ** [comment]
partially fixed, the Anthem sources are using the correct secret, however getting a 500 response. Will investigate further in the morning.

**Comment by kcam01** [comment]
Thanks for looking into this so fast.

**Comment by AnalogJ** [comment]
Just wanted to confirm that I've tested Anthem myself, and it's working correctly now! sorry about that

**Comment by kcam01** [comment]
Thanks I was able to add it but once I connected it The following error pops up
An error occurred while accessing anthem: TypeError: Cannot read properties of null (reading 'state')

`fasten_1`  | 2023/03/17 06:39:36 deprecated: golang.org/x/oauth2: Transport.CancelRequest no longer does anything; use contexts
fasten_1  | time="2023-03-17T06:39:36Z" level=error msg="An error occurred while bulk import of resources from source Get \"https://patient360.anthem.com/P360Member/api/fhir-r4/Patient/<redacted>/$everything\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)" type=web`

**Comment by AnalogJ** [comment]
Hm. I did see that error once, but after retrying Anthem worked. 
Im guessing there's some caching/slow query on the Anthem side that's causing this timeout. 

We could **technically** iterate through each FHIR resource type individually instead of requesting everything, but its kind of a pain in the ass. 

I'll re-open this issue for now.

**Comment by AnalogJ** [comment]
Anthem should be working again. Closing this issue.

**Comment by rbrowning85** [comment]
I am receiving the following error when I try to add Anthem as a source:  

The client application is not known or is not authorized.
